### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kaushalvivek** [AugustKarlstedt/blinkist-scraper#1]
Hi, I was planning on building a scraper for Blinkist and came across your work. I would love to build upon it and contribute to it, by any chance, do you have any documentation files for your code that you forgot to upload?

If not, do you mind putting up a very brief documentation explaining the basics of your code?

Thanks!

**Comment by AugustKarlstedt** [comment]
Sure! I'll add some documentation as soon as I have some time. A quick
overview is that the scraper outputs a file which is then converted to
.HTML files containing the summary content for each book. It worked well
enough for my purposes, but it would be much better to convert to epub :)

**Comment by kaushalvivek** [comment]
@AugustKarlstedt Thank you so much! Looking forward to the documentation, I have some ideas for the project, I'll start adding stuff as soon as get some time from my coursework.

**Comment by AugustKarlstedt** [comment]
@kaushalvivek I've updated the readme. Otherwise, the scrapy code in scraper.py should be self-explanatory. Any additional questions you have, I'm happy to answer.

**Comment by mm-ns** [comment]
I am getting 

I cannot get this to work.. I installed python3, and I get this 

```
Traceback (most recent call last):
  File "generate-html.py", line 8, in <module>
    books = json.load(input_file)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Any idea? First i needed scrapy and i installed it but now this issue arises. The books.json is empty.
